pip installation via setuptool
yzslab/gaussian-splatting-lightning pull request #51
Opened 2024-09-06 09:49 UTC by hardikdava

@yzslab I have added support for pip installation. It can be used as

`pip install git+https://github.com/yzslab/gaussian-splatting-lightning.git`

2024-09-06 09:53 UTC, hardikdava commented
Related to #50

2024-09-06 12:08 UTC, yzslab requested changes

2024-09-06 12:08 UTC, yzslab commented on setup.py
> +    name = "gsplat_lightning",
I prefer not to contain `gsplat`. How about the full name of this repo?

2024-09-06 12:47 UTC, yzslab commented on requirements.txt
> +git+https://gitlab.inria.fr/bkerbl/simple-knn
If install from local is impossible, remember to remove them from git submodule.
If they have to be install from url, shall here also specify the hash for simple-knn?

2024-09-06 13:05 UTC, hardikdava commented on requirements.txt
> +git+https://gitlab.inria.fr/bkerbl/simple-knn
@yzslab I tried some options but could not able to install sub-module through local directory.

2024-09-06 13:05 UTC, hardikdava commented on setup.py
> +install_requires, dependency_links = split_requirements(requirements)
updated the version

2024-09-06 14:27 UTC, hardikdava commented
@yzslab here is the logs of installation. It successfully installed all packages.

```
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from boto3->lightning-cloud>=0.5.38->lightning[pytorch-extra]==2.0.9.post0->gaussian-splatting-lightning==0.1.0) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from boto3->lightning-cloud>=0.5.38->lightning[pytorch-extra]==2.0.9.post0->gaussian-splatting-lightning==0.1.0) (0.10.2)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from requests<4.0->lightning[pytorch-extra]==2.0.9.post0->gaussian-splatting-lightning==0.1.0) (1.7.1)
Requirement already satisfied: executing>=1.2.0 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from stack-data->ipython->mediapy==1.2.2->gaussian-splatting-lightning==0.1.0) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from stack-data->ipython->mediapy==1.2.2->gaussian-splatting-lightning==0.1.0) (2.4.1)
Requirement already satisfied: pure-eval in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from stack-data->ipython->mediapy==1.2.2->gaussian-splatting-lightning==0.1.0) (0.2.3)
Requirement already satisfied: mpmath>=0.19 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from sympy->torch<4.0,>=1.11.0->lightning[pytorch-extra]==2.0.9.post0->gaussian-splatting-lightning==0.1.0) (1.3.0)
Requirement already satisfied: httpcore==1.* in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from httpx->trimesh>=3.21.7->viser==0.2.3->gaussian-splatting-lightning==0.1.0) (1.0.5)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from jsonschema->trimesh>=3.21.7->viser==0.2.3->gaussian-splatting-lightning==0.1.0) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from jsonschema->trimesh>=3.21.7->viser==0.2.3->gaussian-splatting-lightning==0.1.0) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /home/hd/Desktop/python_workspace/supervision/venv/lib/python3.10/site-packages (from jsonschema->trimesh>=3.21.7->viser==0.2.3->gaussian-splatting-lightning==0.1.0) (0.20.0)
Building wheels for collected packages: gaussian-splatting-lightning
  Building wheel for gaussian-splatting-lightning (pyproject.toml) ... done
  Created wheel for gaussian-splatting-lightning: filename=gaussian_splatting_lightning-0.1.0-py3-none-any.whl size=219875 sha256=cb2c5aec794244051a58ba01ab2b7ee30e8b25b241ecc0321314e93450dc9edf
  Stored in directory: /tmp/pip-ephem-wheel-cache-g3yzy5a8/wheels/72/df/8f/b0e27189bb364b389b0a8c30d8ad200b69bc84dc591e4835dd
Successfully built gaussian-splatting-lightning
Installing collected packages: simple-knn, diff-gaussian-rasterization, gaussian-splatting-lightning
Successfully installed diff-gaussian-rasterization-0.0.0 gaussian-splatting-lightning-0.1.0 simple-knn-0.0.0

```

2024-09-06 14:27 UTC, hardikdava commented
@yzslab now, we can also remove `requirements.txt` along with some submodules.

2024-09-07 13:30 UTC, yzslab commented
Hi, take a look whether my updates work for you.

2024-09-07 19:35 UTC, hardikdava commented
@yzslab I will test it out and let you know. Thanks

2024-09-08 09:39 UTC, hardikdava commented
@yzslab I have tested the installation and it is working fine. It is also installing both `diff-gaussian-rasterization` and `simple-knn` as default option.

2024-09-08 09:45 UTC, hardikdava commented
@yzslab I have removed `requirements.txt` file as not needed anymore. You can directly add it to `pyproject.toml` directly. I have some suggestions.

- we can create directly cli for some of `utils` scripts with `pyproject.script` mode.
- Let's add `ruff` for consisting code format.

2024-09-08 09:45 UTC, yzslab approved these changes

2024-09-08 10:22 UTC, yzslab commented
> @yzslab I have removed `requirements.txt` file as not needed anymore. You can directly add it to `pyproject.toml` directly. I have some suggestions.
> 
> * we can create directly cli for some of `utils` scripts with `pyproject.script` mode.
> * Let's add `ruff` for consisting code format.

Sounds great, but I am busy with other things, so I am not going to do this personally now.
You can do it if you want, as long as it does not change the existing code or files too much. Since I did not write test cases for the most parts of this repo, it takes time to validate the correctness.

Do you want to merge this PR now, or wait untill you add further improvements you mentioned?

2024-09-08 10:58 UTC, hardikdava commented
@yzslab 

> Sounds great, but I am busy with other things, so I am not going to do this personally now.
> You can do it if you want, as long as it does not change the existing code or files too much. Since I did not write test cases for the most parts of this repo, it takes time to validate the correctness.

- I will see what I can do with my capabilities. 

> Do you want to merge this PR now, or wait until you add further improvements you mentioned?
- yes, you can merge it now. I will create separate PRs for other things.

2024-09-08 11:01 UTC, merged

2024-09-08 11:01 UTC, yzslab commented
Thanks!